//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bang_.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bang_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Apalosa_Apik_ {
            get {
                object obj = ResourceManager.GetObject("Apalosa_Apik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bandita {
            get {
                object obj = ResourceManager.GetObject("Bandita", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_10kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_10kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_2kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_2kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_2kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_2kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_3kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_3kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_3kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_3kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_4kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_4kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_4kriz_ {
            get {
                object obj = ResourceManager.GetObject("Bang_4kriz_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_5kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_5kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_5kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_5kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_6kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_6kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_6kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_6kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_7kar {
            get {
                object obj = ResourceManager.GetObject("Bang_7kar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_7kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_7kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_8_kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_8_kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_8kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_8kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_9kar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_9kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_9kri_ {
            get {
                object obj = ResourceManager.GetObject("Bang_9kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Akar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Akar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Apik_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Apik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Asrd_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Asrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Jkar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Jkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Kkar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Kkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Ksrd_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Ksrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Qkar_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Qkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bang_Qsrd_ {
            get {
                object obj = ResourceManager.GetObject("Bang_Qsrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bangzezadu {
            get {
                object obj = ResourceManager.GetObject("Bangzezadu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Barel_Kpik_ {
            get {
                object obj = ResourceManager.GetObject("Barel_Kpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Barel_Qpik_ {
            get {
                object obj = ResourceManager.GetObject("Barel_Qpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BartCassidy {
            get {
                object obj = ResourceManager.GetObject("BartCassidy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackJack {
            get {
                object obj = ResourceManager.GetObject("BlackJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CalamityJanet {
            get {
                object obj = ResourceManager.GetObject("CalamityJanet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatBalou_10kar_ {
            get {
                object obj = ResourceManager.GetObject("CatBalou_10kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatBalou_9kar_ {
            get {
                object obj = ResourceManager.GetObject("CatBalou_9kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatBalou_Jkar_ {
            get {
                object obj = ResourceManager.GetObject("CatBalou_Jkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatBalou_Ksrd_ {
            get {
                object obj = ResourceManager.GetObject("CatBalou_Ksrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dostavnik_3srd_ {
            get {
                object obj = ResourceManager.GetObject("Dostavnik_3srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dostavnik_9pik_ {
            get {
                object obj = ResourceManager.GetObject("Dostavnik_9pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duel_8kriz_ {
            get {
                object obj = ResourceManager.GetObject("Duel_8kriz_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duel_Jpik_ {
            get {
                object obj = ResourceManager.GetObject("Duel_Jpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duel_Qkar_ {
            get {
                object obj = ResourceManager.GetObject("Duel_Qkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dynamit_2srd_ {
            get {
                object obj = ResourceManager.GetObject("Dynamit_2srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ElGringo {
            get {
                object obj = ResourceManager.GetObject("ElGringo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hokynarstvi_9kri_ {
            get {
                object obj = ResourceManager.GetObject("Hokynarstvi_9kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hokynarstvi_Qpik_ {
            get {
                object obj = ResourceManager.GetObject("Hokynarstvi_Qpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Indiani_Akar_ {
            get {
                object obj = ResourceManager.GetObject("Indiani_Akar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Indiani_Kkar_ {
            get {
                object obj = ResourceManager.GetObject("Indiani_Kkar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JesseJones {
            get {
                object obj = ResourceManager.GetObject("JesseJones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jourdonnais {
            get {
                object obj = ResourceManager.GetObject("Jourdonnais", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KitCarlson {
            get {
                object obj = ResourceManager.GetObject("KitCarlson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kulomet_10srd_ {
            get {
                object obj = ResourceManager.GetObject("Kulomet_10srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LuckyDuke {
            get {
                object obj = ResourceManager.GetObject("LuckyDuke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mustang_8srd_ {
            get {
                object obj = ResourceManager.GetObject("Mustang_8srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mustang_9srd_ {
            get {
                object obj = ResourceManager.GetObject("Mustang_9srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Odpadlik {
            get {
                object obj = ResourceManager.GetObject("Odpadlik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Panika_8kar_ {
            get {
                object obj = ResourceManager.GetObject("Panika_8kar_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Panika_Asrd_ {
            get {
                object obj = ResourceManager.GetObject("Panika_Asrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Panika_Jsrd_ {
            get {
                object obj = ResourceManager.GetObject("Panika_Jsrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Panika_Qsrd_ {
            get {
                object obj = ResourceManager.GetObject("Panika_Qsrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Patrony {
            get {
                object obj = ResourceManager.GetObject("Patrony", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PaulRegret {
            get {
                object obj = ResourceManager.GetObject("PaulRegret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PedroRamirez {
            get {
                object obj = ResourceManager.GetObject("PedroRamirez", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_10srd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_10srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_6srd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_6srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_7srd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_7srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_8srd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_8srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_9srd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_9srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pivo_Jsrd_ {
            get {
                object obj = ResourceManager.GetObject("Pivo_Jsrd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PostavaZezadu {
            get {
                object obj = ResourceManager.GetObject("PostavaZezadu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remington_Kkri_ {
            get {
                object obj = ResourceManager.GetObject("Remington_Kkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rev_Carabine_Akri_ {
            get {
                object obj = ResourceManager.GetObject("Rev_Carabine_Akri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoseDoolan {
            get {
                object obj = ResourceManager.GetObject("RoseDoolan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salon_5srd_ {
            get {
                object obj = ResourceManager.GetObject("salon_5srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Schofield_Kpik_ {
            get {
                object obj = ResourceManager.GetObject("Schofield_Kpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Scofield_Jkri_ {
            get {
                object obj = ResourceManager.GetObject("Scofield_Jkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Scofield_Qkri_ {
            get {
                object obj = ResourceManager.GetObject("Scofield_Qkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sherif {
            get {
                object obj = ResourceManager.GetObject("Sherif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SidKetchum {
            get {
                object obj = ResourceManager.GetObject("SidKetchum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlabTheKiller {
            get {
                object obj = ResourceManager.GetObject("SlabTheKiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SuzyLafayette {
            get {
                object obj = ResourceManager.GetObject("SuzyLafayette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahoj.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_10kri_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_10kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_2pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_2pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_3pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_3pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_4pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_4pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_5pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_5pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_6pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_6pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_7pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_7pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_8pik_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_8pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_Akri_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_Akri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_Jkri_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_Jkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_Kkri_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_Kkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vedle_Qkri_ {
            get {
                object obj = ResourceManager.GetObject("Vedle_Qkri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vezeni_10pik_ {
            get {
                object obj = ResourceManager.GetObject("Vezeni_10pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vezeni_4srd_ {
            get {
                object obj = ResourceManager.GetObject("Vezeni_4srd_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vezeni_Jpik_ {
            get {
                object obj = ResourceManager.GetObject("Vezeni_Jpik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vice {
            get {
                object obj = ResourceManager.GetObject("Vice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vice2 {
            get {
                object obj = ResourceManager.GetObject("Vice2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volcanic_10kri_ {
            get {
                object obj = ResourceManager.GetObject("Volcanic_10kri_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volcanic_10pik_ {
            get {
                object obj = ResourceManager.GetObject("Volcanic_10pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VultureSam {
            get {
                object obj = ResourceManager.GetObject("VultureSam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap welcome {
            get {
                object obj = ResourceManager.GetObject("welcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WillyTheKid {
            get {
                object obj = ResourceManager.GetObject("WillyTheKid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winchester_8pik_ {
            get {
                object obj = ResourceManager.GetObject("Winchester_8pik_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
